MINIO_DOCKER_LOCAL_PORT?=9000
MINIO_DOCKER_CONTAINER_NAME?=minio
MINIO_DOCKER_CONTAINER_NAME_CLIENT?=$(MINIO_DOCKER_CONTAINER_NAME)-cli
MINIO_DOCKER_USERNAME?=dbfs-dev
MINIO_DOCKER_PASSWORD?=dbfs-dev
