name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64\
          --output "type=image,push=false" \
          -t andrebq/dbfs:latest \
          -f ./Dockerfile \
          .

    - name: Docker Login
      if: success()
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Docker Buildx (push)
      if: success()
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64\
          --output "type=image,push=true" \
          -t andrebq/dbfs:latest \
          -f ./Dockerfile \
          .
